### ISSUE TITLE
SqlServer Pipeline getting id not found error

### ISSUE THREAD

**Issue by mehmetozkaya** [dotnetcore/DotnetSpider#105]
Hi,

I am trying to export spider data into sql server database and table.
Using below codes into custom spider OnInit method;
`AddRequest(string.Format("http://news.baidu.com/ns?word={0}&tn=news&from=news&cl=2&pn=0&rn=20&ct=1", word), new Dictionary<string, dynamic> { { "Keyword", word } });`
`AddEntityType<BaiduSearchEntry>();`
`AddPipeline(new SqlServerEntityPipeline(constr));`

And run spider as a Spider.Run method. Console is giving below error;

`Execute pipeline failed [1]: System.Data.SqlClient.SqlException (0x80131904): Column name 'id' does not exist in the target table or view.
Could not create constraint or index. See previous errors.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()`

BaiduSearchEntry class is same as your sample project. Could you please check it ?

**Comment by zlzforever** [comment]
I submit the new version/design codes, and i think this bug will not repo.
