### ISSUE TITLE
The type initializer for 'DotnetSpider.Infrastructure.SystemInformation' threw an exception.

### ISSUE THREAD

**Issue by kennethhub** [dotnetcore/DotnetSpider#163]
按照Wiki中【第一个简单的爬虫】的步骤，运行后报错
The type initializer for 'DotnetSpider.Infrastructure.SystemInformation' threw an exception.
![image](https://user-images.githubusercontent.com/24538200/78522766-07d63280-7801-11ea-9db0-13ad46a43c55.png)

`Fatal error. System.TypeInitializationException: The type initializer for 'DotnetSpider.Infrastructure.SystemInformation' threw an exception.
 ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   --- End of inner exception stack trace ---
[13:50:35 INF   at DotnetSpider.Agent.AgentService+<ExecuteAsync>d__8.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[DotnetSpider.Agent.AgentService+<ExecuteAsync>d__8, DotnetSpider, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null]](<ExecuteAsync>d__8 ByRef)
]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[DotnetSpider.Agent.AgentService+<ExecuteAsync>d__8, DotnetSpider, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null]](<ExecuteAsync>d__8 ByRef)
   at DotnetSpider.Agent.AgentService.ExecuteAsync(System.Threading.CancellationToken)
Agent register service started   at Microsoft.Extensions.Hosting.BackgroundService.StartAsync(System.Threading.CancellationToken)

   at Microsoft.Extensions.Hosting.Internal.Host+<StartAsync>d__9.MoveNext()
[   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.Extensions.Hosting.Internal.Host+<StartAsync>d__9, Microsoft.Extensions.Hosting, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<StartAsync>d__9 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.Extensions.Hosting.Internal.Host+<StartAsync>d__9, Microsoft.Extensions.Hosting, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<StartAsync>d__9 ByRef)
13:50:35   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(System.Threading.CancellationToken)
    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<RunAsync>d__4.MoveNext()
INF   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<RunAsync>d__4, Microsoft.Extensions.Hosting.Abstractions, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<RunAsync>d__4 ByRef)
]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<RunAsync>d__4, Microsoft.Extensions.Hosting.Abstractions, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<RunAsync>d__4 ByRef)
Statistics service started   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(Microsoft.Extensions.Hosting.IHost, System.Threading.CancellationToken)

   at DotnetSpider.Sample.Program+<Main>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at DotnetSpider.Sample.Program.Main(System.String[])
   at DotnetSpider.Sample.Program.<Main>(System.String[])`
![image](https://user-images.githubusercontent.com/24538200/78527791-72429f00-7810-11ea-8000-501e8b79c2f7.png)

**Comment by zlzforever** [comment]
windows 获取内存的代码有问题，周末更新过一版代码，因为我没有 windows 环境，你可以再测试一下。后面看有不骨 dotnet core 下通用的库引入

**Comment by kennethhub** [comment]
> windows 获取内存的代码有问题，周末更新过一版代码，因为我没有 windows 环境，你可以再测试一下。后面看有不骨 dotnet core 下通用的库引入

nuget程序包没有更新么？还是存在问题

**Comment by kennethhub** [comment]
> windows 获取内存的代码有问题，周末更新过一版代码，因为我没有 windows 环境，你可以再测试一下。后面看有不骨 dotnet core 下通用的库引入

ok 没有问题了

**Comment by andrew2558** [comment]
我也是报这个错误

**Comment by andrew2558** [comment]
![无标题](https://user-images.githubusercontent.com/25080605/80051245-4cc0cf80-854a-11ea-9096-38db511baf01.png)
我的也是出这个问题

**Comment by andrew2558** [comment]
> > windows 获取内存的代码有问题，周末更新过一版代码，因为我没有 windows 环境，你可以再测试一下。后面看有不骨 dotnet core 下通用的库引入
> 
> ok 没有问题了

请问你是怎么解决的？

**Comment by kennethhub** [comment]
> > > windows 获取内存的代码有问题，周末更新过一版代码，因为我没有 windows 环境，你可以再测试一下。后面看有不骨 dotnet core 下通用的库引入
> > 
> > 
> > ok 没有问题了
> 
> 请问你是怎么解决的？

引用最新预览版
